name: update-json

on:
  workflow_dispatch:
  schedule:
    - cron: "45 20 */5 * *"

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: 22
      - name: Overwrite JSON
        run: |
          npm ci
          npx tsx ./json/overwrite.ts
      - name: Set date variable
        run: echo "DATE=$(date '+%y-%m-%d')" >> "$GITHUB_ENV"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: "Update JSON"
          title: "Update JSON ${{ env.DATE }}"
